import { ChallengeTemplate, ChallengeCategory } from '@/types/challenge';

export const CHALLENGE_CATEGORIES: { id: ChallengeCategory; name: string; icon: string; color: string }[] = [
  { id: 'fitness', name: 'Fitness', icon: 'Dumbbell', color: '#FF6B6B' },
  { id: 'productivity', name: 'Productivity', icon: 'Rocket', color: '#4ECDC4' },
  { id: 'digital_detox', name: 'Digital Detox', icon: 'Smartphone', color: '#9B59B6' },
  { id: 'learning', name: 'Learning', icon: 'BookOpen', color: '#3498DB' },
  { id: 'mental_health', name: 'Mental Health', icon: 'Heart', color: '#E91E63' },
];

export const CHALLENGE_TEMPLATES: ChallengeTemplate[] = [
  {
    id: '75_hard',
    name: '75 HARD',
    shortDescription: 'The ultimate mental toughness program',
    fullDescription: '75 HARD is a transformative mental toughness program created by Andy Frisella. It\'s not just a fitness challenge—it\'s a complete lifestyle transformation that builds discipline, confidence, and grit. No modifications, no substitutions, no compromises.',
    category: 'fitness',
    durationDays: 75,
    difficulty: 'advanced',
    icon: 'Flame',
    color: '#FF4500',
    image: 'https://r2-pub.rork.com/generated-images/70865222-e474-4a1a-9f8a-09815711df99.png',
    rating: 4.8,
    participantsCount: 125000,
    isPopular: true,
    isNew: false,
    rules: [
      { id: '1', text: 'Two 45-minute workouts per day (one must be outdoors)', isStrict: true },
      { id: '2', text: 'Follow a diet with zero cheat meals or alcohol', isStrict: true },
      { id: '3', text: 'Drink 1 gallon (3.8L) of water daily', isStrict: true },
      { id: '4', text: 'Read 10 pages of non-fiction', isStrict: true },
      { id: '5', text: 'Take a progress photo every day', isStrict: true },
      { id: '6', text: 'Any missed task = restart from Day 1', isStrict: true },
    ],
    benefits: [
      { id: '1', icon: 'Brain', title: 'Mental Toughness', description: 'Build unbreakable discipline and willpower' },
      { id: '2', icon: 'TrendingUp', title: 'Physical Transformation', description: 'Significant improvements in fitness and body composition' },
      { id: '3', icon: 'Target', title: 'Self-Confidence', description: 'Prove to yourself you can accomplish anything' },
      { id: '4', icon: 'Zap', title: 'Energy Boost', description: 'Experience sustained high energy levels' },
    ],
    dailyTasks: [
      'Morning outdoor workout (45 min)',
      'Second workout (45 min)',
      'Follow your chosen diet',
      'Drink 1 gallon of water',
      'Read 10 pages of non-fiction',
      'Take progress photo',
    ],
    exampleDay: [
      { time: '6:00 AM', activity: 'Outdoor run/walk', duration: '45 min' },
      { time: '7:00 AM', activity: 'Breakfast + 500ml water', duration: '30 min' },
      { time: '12:00 PM', activity: 'Lunch + 1L water', duration: '45 min' },
      { time: '5:00 PM', activity: 'Gym workout', duration: '45 min' },
      { time: '7:00 PM', activity: 'Dinner + reading', duration: '1 hour' },
      { time: '9:00 PM', activity: 'Progress photo + remaining water', duration: '15 min' },
    ],
    failOnMiss: true,
    tags: ['hardcore', 'transformation', 'discipline', 'fitness'],
  },
  {
    id: '75_soft',
    name: '75 SOFT',
    shortDescription: 'A gentler approach to 75 HARD',
    fullDescription: '75 SOFT is a more sustainable version of 75 HARD, designed for those who want to build healthy habits without the extreme strictness. It focuses on consistency and progress over perfection.',
    category: 'fitness',
    durationDays: 75,
    difficulty: 'intermediate',
    icon: 'Leaf',
    color: '#2ECC71',
    image: 'https://r2-pub.rork.com/generated-images/4bf568c1-a9a2-477b-8e28-89cd4d396e7b.png',
    rating: 4.6,
    participantsCount: 89000,
    isPopular: true,
    isNew: false,
    rules: [
      { id: '1', text: 'One 45-minute workout per day', isStrict: false },
      { id: '2', text: 'Practice intuitive eating with minimal processed foods', isStrict: false },
      { id: '3', text: 'Drink 3 liters of water daily', isStrict: false },
      { id: '4', text: 'Read or listen to 10 minutes of personal development', isStrict: false },
      { id: '5', text: 'One rest day per week allowed', isStrict: false },
    ],
    benefits: [
      { id: '1', icon: 'Heart', title: 'Sustainable Habits', description: 'Build habits that last a lifetime' },
      { id: '2', icon: 'Scale', title: 'Balanced Approach', description: 'Achieve results without burnout' },
      { id: '3', icon: 'Smile', title: 'Mental Clarity', description: 'Improved focus and mood' },
    ],
    dailyTasks: [
      'Workout (45 min)',
      'Eat mindfully - whole foods focus',
      'Drink 3L of water',
      'Personal development (10 min reading/podcast)',
    ],
    exampleDay: [
      { time: '7:00 AM', activity: 'Morning workout', duration: '45 min' },
      { time: '8:00 AM', activity: 'Healthy breakfast', duration: '30 min' },
      { time: '12:00 PM', activity: 'Lunch + hydration', duration: '45 min' },
      { time: '8:00 PM', activity: 'Reading/podcast', duration: '15 min' },
    ],
    failOnMiss: false,
    tags: ['sustainable', 'beginner-friendly', 'fitness', 'wellness'],
  },
  {
    id: '30_day_fitness',
    name: '30 Day Fitness',
    shortDescription: 'Progressive bodyweight challenge',
    fullDescription: 'A progressive 30-day bodyweight fitness challenge that gradually increases intensity. Perfect for beginners or those returning to fitness. Start small and build up to impressive numbers!',
    category: 'fitness',
    durationDays: 30,
    difficulty: 'beginner',
    icon: 'Activity',
    color: '#FF6B6B',
    image: 'https://r2-pub.rork.com/generated-images/421f3e9d-46f8-487a-8239-38fa2a7f6fcb.png',
    rating: 4.5,
    participantsCount: 245000,
    isPopular: true,
    isNew: false,
    rules: [
      { id: '1', text: 'Complete daily exercises with proper form', isStrict: false },
      { id: '2', text: 'Rest days are built into the program', isStrict: false },
      { id: '3', text: 'Modify exercises if needed', isStrict: false },
    ],
    benefits: [
      { id: '1', icon: 'TrendingUp', title: 'Progressive Overload', description: 'Gradually build strength and endurance' },
      { id: '2', icon: 'Home', title: 'No Equipment', description: 'Do it anywhere, anytime' },
      { id: '3', icon: 'Clock', title: 'Quick Workouts', description: '15-30 minutes per day' },
    ],
    dailyTasks: [
      'Squats (progressive)',
      'Push-ups (progressive)',
      'Plank hold (progressive)',
      'Lunges (progressive)',
    ],
    exampleDay: [
      { time: 'Any time', activity: 'Warm-up', duration: '5 min' },
      { time: '', activity: 'Main workout', duration: '15-25 min' },
      { time: '', activity: 'Cool-down stretch', duration: '5 min' },
    ],
    failOnMiss: false,
    tags: ['beginner', 'home-workout', 'no-equipment', 'progressive'],
  },
  {
    id: 'couch_to_5k',
    name: 'Couch to 5K',
    shortDescription: 'From zero to running 5K',
    fullDescription: 'The classic Couch to 5K program takes you from complete beginner to running 5 kilometers in just 9 weeks. Using a mix of walking and running intervals, you\'ll build endurance safely and effectively.',
    category: 'fitness',
    durationDays: 63,
    difficulty: 'beginner',
    icon: 'PersonStanding',
    color: '#3498DB',
    image: 'https://r2-pub.rork.com/generated-images/b7bf6d71-4dae-4566-a967-2123d96c2e60.png',
    rating: 4.7,
    participantsCount: 520000,
    isPopular: true,
    isNew: false,
    rules: [
      { id: '1', text: 'Run 3 times per week', isStrict: false },
      { id: '2', text: 'Take rest days between runs', isStrict: true },
      { id: '3', text: 'Don\'t skip ahead in the program', isStrict: false },
    ],
    benefits: [
      { id: '1', icon: 'Heart', title: 'Cardiovascular Health', description: 'Strengthen your heart and lungs' },
      { id: '2', icon: 'Zap', title: 'Energy Boost', description: 'More energy throughout the day' },
      { id: '3', icon: 'Trophy', title: 'Achievement', description: 'Run your first 5K race' },
    ],
    dailyTasks: [
      'Complete scheduled run/walk intervals',
      'Warm-up walk (5 min)',
      'Cool-down walk (5 min)',
      'Stretch after workout',
    ],
    exampleDay: [
      { time: 'Morning/Evening', activity: 'Warm-up walk', duration: '5 min' },
      { time: '', activity: 'Run/walk intervals', duration: '20-30 min' },
      { time: '', activity: 'Cool-down walk', duration: '5 min' },
    ],
    failOnMiss: false,
    tags: ['running', 'beginner', 'cardio', 'outdoor'],
  },
  {
    id: 'miracle_morning',
    name: 'Miracle Morning (SAVERS)',
    shortDescription: 'Transform your mornings, transform your life',
    fullDescription: 'Based on Hal Elrod\'s bestselling book, the Miracle Morning uses the SAVERS method: Silence, Affirmations, Visualization, Exercise, Reading, and Scribing. Wake up earlier to become the best version of yourself.',
    category: 'productivity',
    durationDays: 30,
    difficulty: 'intermediate',
    icon: 'Sunrise',
    color: '#F39C12',
    image: 'https://r2-pub.rork.com/generated-images/18615c5f-aa0e-4a46-ba38-099330c625b3.png',
    rating: 4.6,
    participantsCount: 180000,
    isPopular: true,
    isNew: false,
    rules: [
      { id: '1', text: 'Wake up 1 hour earlier than usual', isStrict: false },
      { id: '2', text: 'Complete all 6 SAVERS activities', isStrict: false },
      { id: '3', text: 'No phone for the first hour', isStrict: false },
    ],
    benefits: [
      { id: '1', icon: 'Brain', title: 'Mental Clarity', description: 'Start each day with focus and intention' },
      { id: '2', icon: 'TrendingUp', title: 'Productivity', description: 'Accomplish more before others wake up' },
      { id: '3', icon: 'Smile', title: 'Positive Mindset', description: 'Build a foundation of positivity' },
    ],
    dailyTasks: [
      'Silence (meditation) - 10 min',
      'Affirmations - 5 min',
      'Visualization - 5 min',
      'Exercise - 20 min',
      'Reading - 20 min',
      'Scribing (journaling) - 10 min',
    ],
    exampleDay: [
      { time: '5:00 AM', activity: 'Wake up, hydrate', duration: '5 min' },
      { time: '5:05 AM', activity: 'Silence/Meditation', duration: '10 min' },
      { time: '5:15 AM', activity: 'Affirmations', duration: '5 min' },
      { time: '5:20 AM', activity: 'Visualization', duration: '5 min' },
      { time: '5:25 AM', activity: 'Exercise', duration: '20 min' },
      { time: '5:45 AM', activity: 'Reading', duration: '20 min' },
      { time: '6:05 AM', activity: 'Scribing/Journaling', duration: '10 min' },
    ],
    failOnMiss: false,
    tags: ['morning-routine', 'productivity', 'mindfulness', 'self-improvement'],
  },
  {
    id: '5am_club',
    name: '5 AM Club',
    shortDescription: 'Own your morning, elevate your life',
    fullDescription: 'Inspired by Robin Sharma\'s book, the 5 AM Club challenge helps you master your mornings with the 20/20/20 formula: 20 minutes of movement, 20 minutes of reflection, and 20 minutes of growth.',
    category: 'productivity',
    durationDays: 21,
    difficulty: 'intermediate',
    icon: 'Clock',
    color: '#9B59B6',
    image: 'https://r2-pub.rork.com/generated-images/e66f2659-aa86-4d73-9cac-fe2f29388197.png',
    rating: 4.5,
    participantsCount: 95000,
    isPopular: false,
    isNew: false,
    rules: [
      { id: '1', text: 'Wake up at 5:00 AM every day', isStrict: true },
      { id: '2', text: 'Follow the 20/20/20 formula', isStrict: false },
      { id: '3', text: 'Go to bed by 10:00 PM', isStrict: false },
    ],
    benefits: [
      { id: '1', icon: 'Zap', title: 'Peak Performance', description: 'Utilize your most productive hours' },
      { id: '2', icon: 'Shield', title: 'Discipline', description: 'Build iron-clad morning discipline' },
      { id: '3', icon: 'Lightbulb', title: 'Creativity', description: 'Access your creative best' },
    ],
    dailyTasks: [
      'Wake at 5:00 AM',
      'Move - Exercise/Stretching (20 min)',
      'Reflect - Meditation/Journaling (20 min)',
      'Grow - Learning/Planning (20 min)',
    ],
    exampleDay: [
      { time: '5:00 AM', activity: 'Wake up', duration: '5 min' },
      { time: '5:05 AM', activity: 'Move - Exercise', duration: '20 min' },
      { time: '5:25 AM', activity: 'Reflect - Meditation', duration: '20 min' },
      { time: '5:45 AM', activity: 'Grow - Learning', duration: '20 min' },
    ],
    failOnMiss: false,
    tags: ['early-riser', 'productivity', 'discipline', 'morning'],
  },
  {
    id: 'deep_work',
    name: 'Deep Work',
    shortDescription: '14 days of focused, distraction-free work',
    fullDescription: 'Based on Cal Newport\'s principles, this challenge helps you develop the ability to focus without distraction on cognitively demanding tasks. Master the art of deep work and produce at an elite level.',
    category: 'productivity',
    durationDays: 14,
    difficulty: 'intermediate',
    icon: 'Target',
    color: '#1ABC9C',
    image: 'https://r2-pub.rork.com/generated-images/c4fc6186-8129-4dc2-92de-ddc3378ba883.png',
    rating: 4.4,
    participantsCount: 67000,
    isPopular: false,
    isNew: true,
    rules: [
      { id: '1', text: 'Complete 4 hours of deep work daily', isStrict: false },
      { id: '2', text: 'Block all social media during deep work', isStrict: true },
      { id: '3', text: 'Use a timer to track focus sessions', isStrict: false },
    ],
    benefits: [
      { id: '1', icon: 'Focus', title: 'Laser Focus', description: 'Develop the ability to concentrate deeply' },
      { id: '2', icon: 'TrendingUp', title: 'Output Quality', description: 'Produce work that matters' },
      { id: '3', icon: 'Clock', title: 'Time Mastery', description: 'Get more done in less time' },
    ],
    dailyTasks: [
      'Morning deep work session (2 hours)',
      'Afternoon deep work session (2 hours)',
      'Block distracting websites/apps',
      'Review daily progress',
    ],
    exampleDay: [
      { time: '9:00 AM', activity: 'Deep work session 1', duration: '2 hours' },
      { time: '11:00 AM', activity: 'Break + shallow work', duration: '1 hour' },
      { time: '2:00 PM', activity: 'Deep work session 2', duration: '2 hours' },
      { time: '4:00 PM', activity: 'Daily review', duration: '15 min' },
    ],
    failOnMiss: false,
    tags: ['focus', 'productivity', 'work', 'concentration'],
  },
  {
    id: 'digital_detox',
    name: 'Digital Detox',
    shortDescription: '7 days to reclaim your attention',
    fullDescription: 'Take back control of your digital life with this 7-day detox. Reduce screen time, eliminate social media, and rediscover the joy of being present in the real world.',
    category: 'digital_detox',
    durationDays: 7,
    difficulty: 'intermediate',
    icon: 'Smartphone',
    color: '#E74C3C',
    image: 'https://r2-pub.rork.com/generated-images/58d440da-b40e-4906-baa7-e2c9a90eb61f.png',
    rating: 4.3,
    participantsCount: 156000,
    isPopular: true,
    isNew: false,
    rules: [
      { id: '1', text: 'Maximum 1 hour of recreational screen time', isStrict: true },
      { id: '2', text: 'No social media', isStrict: true },
      { id: '3', text: 'Phone on Do Not Disturb mode', isStrict: false },
      { id: '4', text: 'No screens 1 hour before bed', isStrict: false },
    ],
    benefits: [
      { id: '1', icon: 'Eye', title: 'Reduced Eye Strain', description: 'Give your eyes a much-needed break' },
      { id: '2', icon: 'Brain', title: 'Mental Clarity', description: 'Clearer thinking without constant notifications' },
      { id: '3', icon: 'Users', title: 'Better Relationships', description: 'More present with loved ones' },
    ],
    dailyTasks: [
      'Track total screen time',
      'No social media apps',
      'Enable Do Not Disturb',
      'Read a physical book',
      'Spend time outdoors',
    ],
    exampleDay: [
      { time: 'Morning', activity: 'Phone-free first hour', duration: '1 hour' },
      { time: 'Daytime', activity: 'Essential phone use only', duration: 'As needed' },
      { time: 'Evening', activity: 'Screen-free activities', duration: '2+ hours' },
      { time: 'Night', activity: 'No screens before bed', duration: '1 hour' },
    ],
    failOnMiss: false,
    tags: ['digital', 'mindfulness', 'screen-time', 'wellness'],
  },
  {
    id: 'gratitude_challenge',
    name: 'Gratitude Challenge',
    shortDescription: '30 days of practicing gratitude',
    fullDescription: 'Transform your mindset through the power of gratitude. This 30-day challenge helps you develop a daily gratitude practice that rewires your brain for positivity and happiness.',
    category: 'mental_health',
    durationDays: 30,
    difficulty: 'beginner',
    icon: 'Heart',
    color: '#E91E63',
    image: 'https://r2-pub.rork.com/generated-images/4281f0a3-c447-4f07-9b18-a7bd9e36b498.png',
    rating: 4.7,
    participantsCount: 210000,
    isPopular: true,
    isNew: false,
    rules: [
      { id: '1', text: 'Write 3 things you\'re grateful for each morning', isStrict: false },
      { id: '2', text: 'Send one gratitude message to someone daily', isStrict: false },
      { id: '3', text: 'End each day reflecting on positive moments', isStrict: false },
    ],
    benefits: [
      { id: '1', icon: 'Smile', title: 'Increased Happiness', description: 'Scientifically proven mood booster' },
      { id: '2', icon: 'Heart', title: 'Better Relationships', description: 'Deepen connections with others' },
      { id: '3', icon: 'Moon', title: 'Improved Sleep', description: 'Fall asleep with positive thoughts' },
    ],
    dailyTasks: [
      'Write 3 morning gratitudes',
      'Send a gratitude message',
      'Evening reflection',
    ],
    exampleDay: [
      { time: 'Morning', activity: 'Write 3 gratitudes in journal', duration: '5 min' },
      { time: 'Afternoon', activity: 'Send thank you message', duration: '5 min' },
      { time: 'Evening', activity: 'Reflect on day\'s blessings', duration: '5 min' },
    ],
    failOnMiss: false,
    tags: ['gratitude', 'mindfulness', 'happiness', 'journaling'],
  },
  {
    id: 'no_complaint',
    name: 'No Complaint Challenge',
    shortDescription: '21 days without complaining',
    fullDescription: 'Based on Will Bowen\'s "A Complaint Free World," this challenge eliminates complaining, criticizing, and gossiping from your life. Use a bracelet as a reminder—switch wrists when you slip up!',
    category: 'mental_health',
    durationDays: 21,
    difficulty: 'advanced',
    icon: 'Ban',
    color: '#8E44AD',
    image: 'https://r2-pub.rork.com/generated-images/a2d1c228-e2cf-490f-bf02-9e0e96a42d0d.png',
    rating: 4.2,
    participantsCount: 78000,
    isPopular: false,
    isNew: false,
    rules: [
      { id: '1', text: 'No complaining, criticizing, or gossiping', isStrict: true },
      { id: '2', text: 'Use a bracelet as reminder', isStrict: false },
      { id: '3', text: 'Switch wrists when you slip up', isStrict: false },
      { id: '4', text: 'Goal: 21 consecutive complaint-free days', isStrict: true },
    ],
    benefits: [
      { id: '1', icon: 'Smile', title: 'Positive Mindset', description: 'Rewire your brain for positivity' },
      { id: '2', icon: 'Users', title: 'Better Relationships', description: 'People enjoy being around you more' },
      { id: '3', icon: 'Zap', title: 'More Energy', description: 'Stop draining energy on negativity' },
    ],
    dailyTasks: [
      'Wear reminder bracelet',
      'Catch yourself before complaining',
      'Reframe negative thoughts',
      'Log slip-ups (if any)',
    ],
    exampleDay: [
      { time: 'All Day', activity: 'Monitor thoughts and speech', duration: 'Ongoing' },
      { time: 'Evening', activity: 'Reflect on the day', duration: '10 min' },
      { time: '', activity: 'Note any slip-ups', duration: '5 min' },
    ],
    failOnMiss: true,
    tags: ['mindset', 'positivity', 'self-awareness', 'mental-health'],
  },
  {
    id: '100_days_of_code',
    name: '100 Days of Code',
    shortDescription: 'Code every day for 100 days',
    fullDescription: 'Join the global #100DaysOfCode movement! Commit to coding for at least one hour every day for 100 days. Share your progress publicly and become part of a supportive community of learners.',
    category: 'learning',
    durationDays: 100,
    difficulty: 'intermediate',
    icon: 'Code',
    color: '#2C3E50',
    image: 'https://r2-pub.rork.com/generated-images/34283ec1-bdca-433a-a843-d7742b119f7d.png',
    rating: 4.6,
    participantsCount: 340000,
    isPopular: true,
    isNew: false,
    rules: [
      { id: '1', text: 'Code for minimum 1 hour every day', isStrict: true },
      { id: '2', text: 'Tweet/post your progress daily', isStrict: false },
      { id: '3', text: 'Work on real projects, not just tutorials', isStrict: false },
    ],
    benefits: [
      { id: '1', icon: 'Code', title: 'Coding Skills', description: 'Dramatically improve your programming abilities' },
      { id: '2', icon: 'Users', title: 'Community', description: 'Connect with fellow developers' },
      { id: '3', icon: 'Briefcase', title: 'Portfolio', description: 'Build projects to showcase' },
    ],
    dailyTasks: [
      'Code for 1+ hour',
      'Work on a project',
      'Share progress publicly',
      'Engage with community',
    ],
    exampleDay: [
      { time: 'Any time', activity: 'Coding session', duration: '1+ hour' },
      { time: 'After coding', activity: 'Commit to GitHub', duration: '5 min' },
      { time: '', activity: 'Share progress', duration: '5 min' },
    ],
    failOnMiss: false,
    tags: ['coding', 'programming', 'learning', 'tech'],
  },
  {
    id: '30_day_language',
    name: '30 Day Language Challenge',
    shortDescription: 'Learn a new language in 30 days',
    fullDescription: 'Immerse yourself in a new language for 30 days. With daily practice, conversation exercises, and immersion techniques, you\'ll make significant progress in just one month.',
    category: 'learning',
    durationDays: 30,
    difficulty: 'beginner',
    icon: 'Languages',
    color: '#27AE60',
    image: 'https://r2-pub.rork.com/generated-images/ae82b8d6-986b-4244-b170-29bfd936c79e.png',
    rating: 4.4,
    participantsCount: 128000,
    isPopular: false,
    isNew: true,
    rules: [
      { id: '1', text: '30 minutes of active study daily', isStrict: false },
      { id: '2', text: 'Practice speaking out loud', isStrict: false },
      { id: '3', text: 'Immerse yourself in the language', isStrict: false },
    ],
    benefits: [
      { id: '1', icon: 'Globe', title: 'New Language', description: 'Open doors to new cultures' },
      { id: '2', icon: 'Brain', title: 'Cognitive Benefits', description: 'Boost brain power and memory' },
      { id: '3', icon: 'Users', title: 'Communication', description: 'Connect with more people' },
    ],
    dailyTasks: [
      'Vocabulary study (10 min)',
      'Grammar practice (10 min)',
      'Speaking practice (10 min)',
      'Media immersion (optional)',
    ],
    exampleDay: [
      { time: 'Morning', activity: 'Vocabulary flashcards', duration: '10 min' },
      { time: 'Afternoon', activity: 'Grammar lesson', duration: '10 min' },
      { time: 'Evening', activity: 'Speaking practice', duration: '10 min' },
    ],
    failOnMiss: false,
    tags: ['language', 'learning', 'education', 'skills'],
  },
];

export const DURATION_FILTERS = [
  { id: 'all', label: 'All' },
  { id: 'short', label: '1-14 days' },
  { id: 'medium', label: '15-30 days' },
  { id: 'long', label: '30+ days' },
];

export const getChallengesByCategory = (category: ChallengeCategory): ChallengeTemplate[] => {
  return CHALLENGE_TEMPLATES.filter(c => c.category === category);
};

export const getPopularChallenges = (): ChallengeTemplate[] => {
  return CHALLENGE_TEMPLATES.filter(c => c.isPopular);
};

export const getNewChallenges = (): ChallengeTemplate[] => {
  return CHALLENGE_TEMPLATES.filter(c => c.isNew);
};

export const getChallengeById = (id: string): ChallengeTemplate | undefined => {
  return CHALLENGE_TEMPLATES.find(c => c.id === id);
};
